env:
  node: true
  es2021: true
  jest/globals: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
parser: "@typescript-eslint/parser"
rules:
  no-constant-condition:
    - error
    - checkLoops: false
plugins:
  - "jest"
  - "@typescript-eslint"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: "./tsconfig.json"
