name: "Hugo Artifact Action"
author: "Ace Archive"
description: >
  A GitHub action used to build the Ace Archive site using Hugo.
inputs:
  artifacts_path:
    description: >
      The path of the directory in the git repository to write the artifact page
      markdown files to.
    required: true
  metadata_path:
    description: >
      The path of the JSON file in the archive to write the global metadata to.
    required: true
  endpoint:
    description: >
      The API endpoint for the Ace Archive API.
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
