name: "Hugo Artifact Action"
author: "Ace Archive"
description: >
  A GitHub action used to build the Ace Archive site using Hugo.
inputs:
  path:
    description: >
      The path of the directory in the git repository to write the markdown
      files to.
    required: true
  artifacts:
    description: >
      A JSON array containing the metadata for each artifact.
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
