name: "Hugo Artifact Action"
author: "Ace Archive"
description: >
  A GitHub action used to build the Ace Archive site using Hugo.
inputs:
  endpoint:
    description: >
      The API endpoint for the Ace Archive API.
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
